### PR TITLE
Replace `PresetCommand` with `Command`

### PR DESCRIPTION
**Pull request by CupOfTea696**
The `PresetCommand` itself doesn't use the `Macroable` trait, the base `Command` class does, so that should be the class the ide helpers are added for.

### CODE REVIEW

**Comment by KristofMorva** [comment]
Thank you, do you happen to know if it's a longstanding bug in this package, or has it changed in one of the versions? I have updated this list a long time ago, it might be worth to check which `Macroable` classes have changed / been removed / were added.

**Comment by CupOfTea696** [comment]
@KristofMorva Sorry, I have no idea

**Comment by KristofMorva** [comment]
All right, I'll check it out :)

**Comment by KristofMorva** [comment]
Looks valid, custom Artisan Console Commands extend `Illuminate\Console\Command`, which without this PR seems to be unsupported.

Thanks!

**Pull request merged**
