### PR TITLE
Add support for Laravel 10

### PR DESCRIPTION
**Pull request by sixmonkey**
Thanks for that great package! Please add support for laravel 10. Thanks!

### CODE REVIEW

**Comment by frankiejarrett** [comment]
@KristofMorva we can implement workarounds but it'd be great if this can be merged soon

**Comment by KristofMorva** [comment]
> @KristofMorva we can implement workarounds but it'd be great if this can be merged soon

Hey, since I'm not part of the PHP ecosystem anymore and can't check myself: can you confirm that it works as-is? :)

**Comment by frankiejarrett** [comment]
@KristofMorva yes I can confirm this PR works, I get custom macros definitions in my IDE on Laravel 10.6 and PHP 8.2

**Comment by KristofMorva** [comment]
> @KristofMorva yes I can confirm this PR works, I get custom macros definitions in my IDE on Laravel 10.6 and PHP 8.2

Great, thank you! I really don't know how it's possible that this code still works after all these years... :D

**Pull request merged**
