### PR TITLE
Add support for Laravel 7

### LINKED ISSUE #16: Add support Laravel 7
Laravel 7 is released, but composer.json restricts to 5 and 6.

### PR DESCRIPTION
**Pull request by Teakowa**
Fix #16 

And add minimum PHP version 7.0 required.

### CODE REVIEW

**Comment by KristofMorva** [comment]
Hey @Teakowa, thank you!
Did you have a chance to test it out, is everything working correctly? No Laravel 7.0 structural changes affected this package?

**Comment by Teakowa** [comment]
@KristofMorva Ok, I will test further.

If there have some problem, I will feedback and update this PR.

**Comment by KristofMorva** [comment]
> 
> 
> @KristofMorva Ok, I will test further.
> 
> If there have some problem, I will feedback and update this PR.

Sorry, I have seen your comment in the issue too late, so I wasn't sure if you tested it beforehand :)

Nevertheless, it never hurts to check it out twice, please let me know if you stumble upon any issue (or if you don't).

**Comment by Teakowa** [comment]
Sorry for late reply.

It seems that Response macro will be generated to Routing, but that's autocomplete not working, example:

```php
// ApiResponseServiceProvider.php
use Illuminate\Support\Facades\Response;

Response::macro('success', function ($data = [], $message = 'success') {
    return new JsonResponse([
        'code' => 0,
        'data' => $data,
        'message' => $message
    ], 200);
});

// _ide_macros.php
namespace Illuminate\Routing {
    class ResponseFactory
    {
        public static function success($data, string $status = 'success')
        {
        }
    }
}
```

image

It seems that response macro need generate to `Illuminate\Contracts\Routing\ResponseFactory` or `Illuminate\Http\Response`, it can be works.

```php
// _ide_macros.php
namespace Illuminate\Http {
    class Response
    {
        public static function success($data, string $status = 'success')
        {
        }
    }
}
```
image

I don't think this is a bug of Laravel 7, it seems to exist long ago(/barryvdh/laravel-ide-helper#531).

Actually, I didn't find any bugs caused by upgrading to Laravel 7.

**Comment by KristofMorva** [comment]
Thank you for looking into it!
The problem seems to be strange, as `\Illuminate\Http\Response` is in the list of macro classes. Anyways, this problem is not new then, meaning that the current version of this package has the same problem, right? If that's the case, then I'm confident enough to pull this in into a new version.

**Comment by Teakowa** [comment]
So can the framework require now be raised to 5.5? or just add support for 7.0?

**Comment by KristofMorva** [comment]
Well, the Laravel 5.0 defines `"php": ">=5.4.0"`, does not restrict PHP 7.0, so theoretically you can still use for example Laravel 5.4 with PHP 7.0; so it makes sense to pop up the PHP version requirement, but leave the Laravel requirement as-is, as it is actually supported.

**Comment by Teakowa** [comment]
Add minimum PHP version 7.0 required.

**Comment by KristofMorva** [comment]
Awesome, thanks!

**Comment by willsmanley** [comment]
So does this PR add autocomplete for macros?

**Comment by KristofMorva** [comment]
Um... this PR adds support for Laravel 7. The point of the whole package is to provide IDE support for macros :)

**Comment by willsmanley** [comment]
Sorry I was on the other Laravel IDE helper package by barry and thought that this was a PR for his package.

**Pull request merged**
