### PR TITLE
Only add backslash when return type is an object

### PR DESCRIPTION
**Pull request by mortenscheel**
Sorry about this. This should fix it.

### CODE REVIEW

**Comment by mortenscheel** [comment]
Wait - I'll just add nullable types and default values while I'm add it.

**Comment by mortenscheel** [comment]
Okay, I've added `?` before optional parameters and nullable return types. I didn't notice that you already had support for default values.

**Comment by mikemand** [comment]
I tested this against my reproduction steps in #21 and it works. 👍 

Closes #21

**Comment by KristofMorva** [comment]
Awesome, thanks @mortenscheel for the fix and @mikemand for checking it back!

**Pull request merged**
